# Generated by Django 4.0.3 on 2023-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessurl',
            name='testURL',
            field=models.URLField(),
        ),
    ]
