# Generated by Django 4.0.3 on 2023-05-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugang', '0003_remove_resultinfo_servertime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultinfo',
            name='speedRanking',
        ),
    ]
