# Generated by Django 4.0.3 on 2023-05-10 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testURL', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='resultInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pingSpeed', models.FloatField()),
                ('upSpeed', models.FloatField()),
                ('downSpeed', models.FloatField()),
                ('serverTime', models.TimeField()),
                ('speedRanking', models.IntegerField()),
                ('toAccessURL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugang.accessurl')),
            ],
        ),
    ]
